### ISSUE TITLE
Integrating Sentry outside request context in AdonisJS

### ISSUE THREAD

**Issue by joaosilva0345** [RomainLanz/sentry#2]
Hi, everyone!

I am using Sentry integrated with the IoC Container and HttpContext in my AdonisJS application. The installation and configuration of Sentry are working perfectly to capture errors within the HTTP request context. However, I have no idea how to integrate Sentry outside of this context, specifically in asynchronous methods and jobs.

Below is an example of a job I am using:

``` typescript
import { Job } from '@rlanz/bull-queue'

export default class TestJob extends Job {
  static get $$filepath() {
    return import.meta.url
  }

  async handle() {
   // How do I log a message in Sentry?
   }

  async rescue() {}
}
```

Can anyone guide me on how to access the Sentry service outside the request context, in asynchronous functions and jobs?

Thank you!

**Comment by joaosilva0345** [comment]
I arrived at the following solution, but I don't know if it is correct:

```ts
import { inject } from '@adonisjs/core'
import { Job } from '@rlanz/bull-queue'
import { Sentry } from '@rlanz/sentry'

@inject()
export default class TestJob extends Job {
  constructor(protected sentry: Sentry) {
    super()
  }

  static get $$filepath() {
    return import.meta.url
  }

  async handle() {
    console.log(this.sentry.getUser()) // test sentry
    return
  }

  async rescue() {}
}
```

Is the only way to access the sentry out of context through injection?

**Comment by joaosilva0345** [comment]
I arrived at the following solution, but I don't know if it is correct:

```ts
import { inject } from '@adonisjs/core'
import { Job } from '@rlanz/bull-queue'
import { Sentry } from '@rlanz/sentry'

@inject()
export default class TestJob extends Job {
  constructor(private sentry: Sentry) {
    super()
  }

  static get $$filepath() {
    return import.meta.url
  }

  async handle() {
    console.log(this.sentry.getUser()) // test sentry
    return
  }

  async rescue() {}
}
```
**Is the only way to access the sentry out of context through injection?**

**Comment by RomainLanz** [comment]
Hey @joaosilva0345! 👋🏻 

Yes, it is the way!

**Comment by joaosilva0345** [comment]
Thank you.

**Comment by parker-codes** [comment]
I tried to do the same in a command, but calling `super()` is a bit more complex. @RomainLanz do you have an idea of how I might access Sentry from a command? `startApp` is set to true, which I thought could load it up automatically for me.

![SCR-20241209-pifp](https://github.com/user-attachments/assets/58f18ff8-9cf1-40c6-82cf-b84e07b4b16f)

**Comment by RomainLanz** [comment]
You can inject inside the `run` method directly!

```ts
import { Sentry } from '@rlanz/sentry'

export default class CustomCommand extends BaseCommand {
  static commandName = 'custom:command'
  static description = ''

  static options: CommandOptions = {
    startApp: true,
  }

  @inject()
  run(sentry: Sentry) {
    // ...  
  }
}
```

**Comment by parker-codes** [comment]
Oh, this is neat! Thank you @RomainLanz!
